---
- name: Converge
  hosts: all
  tasks:

    - name: Install just the executable
      include_role:
        name: maresb.micromamba

    - name: Create condauser
      user:
        name: condauser

    - name: Copy lockfile
      copy:
        src: "{{ playbook_dir }}/conda-linux-64.lock"
        dest: "/home/condauser/conda-linux-64.lock"
        mode: "644"

    - name: Create user-based prefix at /home/condauser/micromamba-test
      include_role:
        name: maresb.micromamba
      vars:
        ansible_user: condauser
        root_prefix: ~/micromamba-test
        root_prefix_condarc:
          channels:
            - conda-forge
        file: /home/condauser/conda-linux-64.lock

    - name: Test /home/condauser/micromamba-test
      include: tasks/test-prefix.yml
      vars:
        user: condauser
        prefix: ~/micromamba-test
        test_command: s3fs --version

    - name: Create a prefix, install packages, create .condarc in /opt/conda
      include_role:
        name: maresb.micromamba
      vars:
        root_prefix: /opt/conda
        packages:
          - s3fs-fuse
        root_prefix_condarc:
          channels:
            - conda-forge
          show_channel_urls: true

    - name: Workaround for mamba-org/mamba#1139
    # https://github.com/mamba-org/mamba/issues/1139
      file:
        path: /opt/conda/etc/profile.d
        state: directory
        mode: "u+rwx,g+rx,o+rx"

    - name: Create condauser
      user:
        name: condauser2

    - name: Test /opt/conda
      include: tasks/test-prefix.yml
      vars:
        user: condauser2
        prefix: /opt/conda
        test_command: s3fs --version
